import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import QueryProvider from "@/components/common/QueryProvider";
import ReduxProvider from "@/components/common/ReduxProvider";
import { SessionProvider } from "next-auth/react";
import NextSessionProvider from "@/components/common/NextSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: " %s | UPlus ",
    default: "Ureca| UPlus ",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextSessionProvider>
          <QueryProvider>
            <ReduxProvider>
              <Navbar />
              {children}
            </ReduxProvider>
          </QueryProvider>
        </NextSessionProvider>
      </body>
    </html>
  );
}
