import { Metadata } from "next";

// server component -> client component(use~) 에서는 사용 X
export const metadata: Metadata = {
  title: "도서 정보",
  description: "Generated by create next app",
};

export default function BookLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {children}
      <h1>Hello~~</h1>
    </div>
  );
}
